eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: https://erp-eureka.herokuapp.com/eureka/
  instance:
    hostname: erp-eureka.herokuapp.com
    nonSecurePort: 80
logging:
  file:
    name: C:\logs\springboot.log
  level:
    root: INFO
    tn:
      esprit:
        repository: INFO
        service: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{36} - %msg%n'
server:
  port: 8083
spring:
  application:
    name: recruteur-microservice
  datasource:
    password: evLqTiZoa1
    url: jdbc:mysql://remotemysql.com:3306/zllHlDSaiG?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: zllHlDSaiG 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true